### ISSUE TITLE
perbaikan persentasi 1

### ISSUE THREAD

**Issue by akhmadsyarif04** [dipaadipati/MI-Nurul-Islam-KM5#1]
1. perbaikan pada galery terpkan halaman, pencarian
2. CRUD pendaftaran siswa/siswi baru
3. CRUD kurikulum
4. CRUD Artikel Kegiatan (seperti: perpisahan, 17 agustusan, tour studi dll)

**Comment by dipaadipati** [comment]
1. ba2f31255c4d1598ddde5ddb0de6c7e2fb03a2a5
2. 7d9a6e85ec1cf967e431eeff7249eec447e72d2c
3. 63bb0ad89dcb40750a3fb774cdb3a2a93a4853e2

**Comment by dipaadipati** [comment]
4. 3b76dcb0f81d7ba1ec3c21d929ef49fa501f4e5a
