### ISSUE TITLE
perbaikan 2

### ISSUE THREAD

**Issue by akhmadsyarif04** [dipaadipati/MI-Nurul-Islam-KM5#2]
- [x] CRUD untuk pelajaran yang digunakan 
- [x] pendaftaran siswa baru kurang data dan persyaratan yang diupload
- [x] untuk galeri san kegiatan filename gambar upload gambar jangan nama gambar yg sudah tersedia
- [x] untuk galeri dan kegiatan bagian isi gunakan tinymce

**Comment by dipaadipati** [comment]
1. 5e23fa2383b1e873ea9a0a29a97e90faa379fdd1

**Comment by dipaadipati** [comment]
2. eeed906ef8925e4c161b88291d96496c41903442
3. 2873c78124fee2a251cc9d7881382369c7dc7d7e

**Comment by dipaadipati** [comment]
4. b4f1151805cfbf09355dc631a2a147e23043699c
